# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'timetracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for timetracker
  pod 'RealmSwift'

  target 'timetrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'timetrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
